"""empty message

Revision ID: e68c7cd5678e
Revises: 236f1d36b226
Create Date: 2020-07-17 11:51:31.173700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68c7cd5678e'
down_revision = '236f1d36b226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_me', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_me')
    # ### end Alembic commands ###
